# Generated by Django 6.0.2 on 2026-02-23 16:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_apellido', models.CharField(max_length=200)),
                ('dni', models.CharField(max_length=20, unique=True)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('marca_modelo', models.CharField(max_length=100)),
                ('identificador', models.CharField(help_text='IMEI o Número de Serie', max_length=50)),
                ('password', models.CharField(blank=True, max_length=50, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipos', to='gestion.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Ficha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('ING', 'Ingresado'), ('DIA', 'En Diagnóstico'), ('APR', 'Esperando Aprobación'), ('REP', 'En Reparación'), ('LST', 'Reparado / Listo'), ('NRE', 'No Reparado'), ('REJ', 'Presupuesto Rechazado'), ('ENT', 'Entregado')], default='ING', max_length=3)),
                ('falla_cliente', models.TextField()),
                ('obs_recepcion', models.TextField(help_text='Estado físico y accesorios')),
                ('costo_repuesto', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('costo_mo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('resumen_trabajo', models.TextField(blank=True)),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.equipo')),
                ('tecnico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FotoFicha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='fotos/%Y/%m/%d/')),
                ('descripcion', models.CharField(blank=True, max_length=100)),
                ('ficha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='gestion.ficha')),
            ],
        ),
    ]
