# Generated by Django 6.0.2 on 2026-02-24 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ficha',
            name='estado',
            field=models.CharField(choices=[('ING', 'Ingresado'), ('DIA', 'En Diagnóstico'), ('APR', 'Esperando Aprobación'), ('REP', 'En Reparación'), ('LST', 'Reparado'), ('NRE', 'No Reparado'), ('REJ', 'Presupuesto Rechazado'), ('ENT', 'Entregado'), ('ABD', 'Abandonado')], default='ING', max_length=3),
        ),
    ]
