# Generated by Django 6.0.2 on 2026-02-27 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_repuesto_repuestoutilizado'),
    ]

    operations = [
        migrations.AddField(
            model_name='ficha',
            name='repuesto_stock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fichas_asignadas', to='gestion.repuesto'),
        ),
    ]
