# Generated by Django 6.0.2 on 2026-03-02 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_ficha_repuesto_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='ficha',
            name='eliminado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ficha',
            name='fecha_eliminacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
